# Generated by Django 5.0.6 on 2024-11-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_alter_userreg_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
