# Generated by Django 5.0.6 on 2024-11-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0003_alter_userreg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='pro_pic',
            field=models.FileField(blank=True, null=True, upload_to='pro_pic/'),
        ),
    ]
