# Generated by Django 5.0.6 on 2024-11-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0004_userreg_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='pro_pic',
            field=models.FileField(blank=True, default='pro_pic/user-profile-icon.jpg', null=True, upload_to='pro_pic/'),
        ),
    ]
