# Generated by Django 5.0.6 on 2024-11-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0006_postmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='liked_users',
            field=models.ManyToManyField(default=0, related_name='liked_posts', to='detect.userreg'),
        ),
    ]
