# Generated by Django 5.0.6 on 2024-11-14 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0007_alter_postmodel_liked_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detect.postmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detect.userreg')),
            ],
        ),
    ]
