# Generated by Django 5.0.6 on 2024-11-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0008_commentsectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
